config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'lists#index'
  resources :lists, except: [:edit, :update] do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  validates :comment, length: { minimum: 6 }
  belongs_to :movie
  belongs_to :list
  validates :movie_id, uniqueness: { scope: :list_id, message: "is already in the list"}
end

app/models/list.rb
class List < ApplicationRecord
  validates :name, presence: true
  validates :name, uniqueness: true
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title, :overview, presence: true
  validates :title, uniqueness: true
  has_many :bookmarks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    if @bookmark.save
      redirect_to list_path(@bookmark)
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to bookmarks_path
  end
  private

  def bookmark_params
    params.require(:bookmark).permit(:movie_id, :list_id, :comment)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/index.html.erb
<div class="navbar ">
  <div class="container-fluid">

    <p>BOOKMARKS INDEX not used</p>
    <%= link_to "Add a bookmark", "bookmarks/new", class: "nav-link btn btn-outline-primary" %>
  </div>
</div>

app/views/bookmarks/new.html.erb
<div class="navbar ">
  <div class="container-fluid">

    <p>ADD A NEW BOOKMARK</p>
    <%= link_to "Back to Bookmarks", "bookmarks", class: "nav-link btn btn-outline-primary" %>
  </div>
</div>

<%= simple_form_for @bookmark do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie, collection: Movie.all, prompt: "Choose a Movie" %>
  <%= f.association :list %>
  <%= f.button :submit %>
<% end %>

app/views/bookmarks/show.html.erb
<div class="navbar ">
  <div class="container-fluid">

    <p>SHOW BOOKMARKS</p>
    <%= link_to "Back to Bookmarks", "bookmarks", class: "nav-link btn btn-outline-primary" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="navbar">
  <div class="container-fluid">

    <p>LISTS</p>
    <%= link_to "Add a list", "lists/new", class: "nav-link btn btn-outline-primary" %>
  </div>
</div>

<div class='container'>
  <h1>All the lists (<%= @lists.count  %>)</h1>
  <% @lists.each do |list| %>
     <h2><%= link_to list.name, list_path(list)%></h2>
  <% end %>
</div>

<%= link_to "Create a movie list", new_list_path, class: " btn btn-outline-success" %>

app/views/lists/new.html.erb
<div class="navbar ">
  <div class="container-fluid">

    <p>ADD A NEW LIST</p>
    <%= link_to "Back to lists", lists_path, class: "nav-link btn btn-outline-primary" %>
  </div>
</div>
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <h3>Create a new list</h3>
        <%= simple_form_for @list do |f| %>
          <%= f.input :name, placeholder: 'Drama' %>
          <%= f.submit class: 'btn btn-flat' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/lists/show.html.erb
<div class="navbar ">
  <div class="container-fluid">

    <p>SHOW LISTS</p>
    <%= link_to "Back to Lists", lists_path, class: "nav-link btn btn-outline-primary" %>
  </div>
</div>

<div class="position-relative">
    <h1><%= @list.name %></h1>
</div>